{% set name = "backstage" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backstage-{{ version }}.tar.gz
  sha256: 51f9d04746247ab2baeb4465c23bb01a7a08c41f76848539e83fe9f6d54a1d1c

build:
  entry_points:
    - backstage = backstage.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - oscan
    - python >=3.5
    - shared
    - subrun

test:
  source_files:
    - tests
  imports:
    - backstage
  commands:
    - pip check
    - backstage --help
    # Remove test suite for now
    # - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/pyrustic/backstage
  summary: Extensible command line tool for managing software projects
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
