{% set name = "backstage" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backstage-{{ version }}.tar.gz
  sha256: 54f433337de9109608022f1cec09374ca16fb814ec2069b3059f64742700d7c9

build:
  entry_points:
    - backstage = backstage.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - jesth
    - oscan
    - python >=3.5
    - shared
    - subrun

test:
  source_files:
    - tests
  imports:
    - backstage
  commands:
    - pip check
    - echo "[task1]" >> backstage.task
    - echo "pass" >> backstage.task
    - backstage --help
    # Remove test suite for now
    # - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/pyrustic/backstage
  summary: Extensible command line tool for managing software projects
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
